### ISSUE TITLE
structure.md におけるdatabaseディレクトリ節の訳修正

### ISSUE THREAD

**Issue by michi-h0623** [laravel-ja/ja-docs-6.x#10]
# structure.md

## original-en
The Database Directory

The `database` directory contains your database migrations, model factories, and seeds. If you wish, you may also use this directory to hold an SQLite database.

## translation-ja

databaseディレクトリ

`database`フォルダはデータベースのマイグレーションとモデルファクトリ、初期値設定（シーディング）を配置します。ご希望であれば、このファイルをSQLiteデータベースの設置場所としても利用できます。

## 修正案

`database`フォルダはデータベースのマイグレーションとモデルファクトリ、初期値設定（シーディング）を配置します。ご希望であれば、このディレクトリをSQLiteデータベースの設置場所としても利用できます。

## 備考
読みながら疑問に思ったので...

**Comment by HiroKws** [comment]
ありがとうございました。修正しました。
