### ISSUE TITLE
facades.md におけるリアルタイムファサード節のtypo/訳修正

### ISSUE THREAD

**Issue by michi-h0623** [laravel-ja/ja-docs-6.x#11]
#  facades.md
## original-en
Real-Time Facades
Using real-time facades, you may treat any class in your application as if it were a facade. To illustrate how this can be used, let's examine an alternative. For example, let's assume our Podcast model has a publish method. However, in order to publish the podcast, we need to inject a Publisher instance:
## translation-ja
リアルタイムファサード
リアルタムファサードを使用すれば、アプリケーション中のどんなクラスでも、ファサードとして取り扱えます。活用法を示すために、新しいテストの手法を撮ってみましょう。例として、Podcastモデルがpublishメソッドを持っているとしましょう。しかしポッドキャストを公開(publish)するには、Publisherインスタンスを注入する必要があるとします。
## 修正案
リアルタイムファサード
リアルタイムファサードを使用すれば、アプリケーション中のどんなクラスも、ファサードのように取り扱えます。活用法を示すために、新しいテストの手法を取ってみましょう。例として、Podcastモデルがpublishメソッドを持っているとしましょう。しかしポッドキャストを公開(publish)するには、Publisherインスタンスを注入する必要があるとします。
## 備考
as if were a facade = まるでファサードのように？

**Comment by michi-h0623** [comment]
## original-en
Injecting a publisher implementation into the method allows us to easily test the method in isolation since we can mock the injected publisher. However, it requires us to always pass a publisher instance each time we call the publish method. Using real-time facades, we can maintain the same testability while not being required to explicitly pass a Publisher instance. To generate a real-time facade, prefix the namespace of the imported class with Facades:
## translation-ja
メソッドへPublisherの実装を注入することにより、注入するpublisherをモックできるため、メソッドを簡単にメソッドを他と切り離してテストできます。しかし、publishメソッドを呼び出すごとに、publisherインスタンスを常に渡す必要があります。リアルタイムファサードを使用すれば、同じてスタビリティを保ちながらも、明確にPublisherインスタンスを渡す必要がなくなります。リアルタイムファサードを作成するには、インポートするクラスのプレフィックスとして、Facade名前空間を付けます。
## 修正案
メソッドへPublisherの実装を注入することにより、注入するpublisherをモックできるため、メソッドを単独で簡単にテストできます。しかし、publishメソッドを呼び出すごとに、publisherインスタンスを常に渡す必要があります。リアルタイムファサードを使用すれば、同じテスタビリティを保ちながらも、明示的にPublisherインスタンスを渡す必要がなくなります。リアルタイムファサードを作成するには、インポートするクラスのプレフィックスとして、Facade名前空間を付けます。

**Comment by HiroKws** [comment]
ありがとうございます。翻訳を全体的に推考しました。
