### ISSUE TITLE
authentication.mdの誤訳と思われる部分

### ISSUE THREAD

**Issue by HASHIMOTO-Takafumi** [laravel-ja/ja-docs-6.x#12]
> たとえばこのメソッドは$user->getAuthPassword()の値と$credentials['password']をHash::makeで値を比較します。

`を`が重複して何を比較するか不明瞭になっています。`Hash::makeで値`は`Hash::makeで処理した値`などのミスでしょうか。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。makeはcheckメソッドの間違いです。当該セクションの和文を推考しました。
