### ISSUE TITLE
ドキュメントのfooter内文言のtypo

### ISSUE THREAD

**Issue by eltociear** [laravel-ja/ja-docs-6.x#14]
ドキュメントの全ページに表示されている下記のfooterの文言に関してなのですが
IssuesがIsuuesにタイポしているようです。

誤

> 翻訳抜け・タイポ・誤訳等の報告はGitHubのIsuuesからお知らせください。

正
> 翻訳抜け・タイポ・誤訳等の報告はGitHubのIssuesからお知らせください。

ご確認お願いいたします🐾

**Comment by HiroKws** [comment]
ありがとうございます。原文の翻訳ではありませんので、別のプライベートリポジトリで管理しています。そちらで修正しました。本日翻訳へ原文の修正点を適用後に公開しますので、その時点で同時にreadouble.comへ反映予定です。

**Comment by eltociear** [comment]
ご確認ありがとうございました。

対応ありがとうございます。
