### ISSUE TITLE
ブロードキャストの本文中にtypo

### ISSUE THREAD

**Issue by ryder472** [laravel-ja/ja-docs-6.x#16]
https://readouble.com/laravel/6.x/ja/broadcasting.html

>CSRFトークン
>Laravel Echoは、現在のセッションのCSRFトークンへアクセスする必要があります。アプリケーションのhead HTML要素を確認し、SCRFトークンを含むようにmetaタグを定義してください。

誤
>SCRFトークン

正
>CSRFトークン

よろしくお願いいたします｡

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
