### ISSUE TITLE
delimiterの和訳

### ISSUE THREAD

**Issue by t-9** [laravel-ja/ja-docs-6.x#19]
68ee2901d19a71993e7bb9538aab31708f7bc3f7
こちらのプルリクエストを送った者です。

"delimiter"の一般的な和訳は「デミリタ」ではなく，「デリミタ」ではないでしょうか。
こちらでプルリクエストを送ったのは「デリミタ」ですが，下記のコミットで修正してくださった部分が「デミリタ」になっています。

5d4cd7edb5c3661723ad3962cdece1803d569619
e39a025ad0bfac4228bebb17d08da87632f6accb

**Comment by HiroKws** [comment]
ありがとうございます。readouble.comへの反映は、明日の定期更新に合わせて同時に行います。

2020年2月16日(日) 14:30 Chikage <notifications@github.com>:
