### ISSUE TITLE
Laravel 6.x API認証 に「不必要ありません。」という誤字

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#20]
https://readouble.com/laravel/6.x/ja/api-authentication.html
Laravel 6.x API認証

「そのため、bcryptなどの遅いハッシュ方法は不必要ありません。」
という部分の
「不必要ありません」が誤字と思われる。

**Comment by HiroKws** [comment]
ありがとうございます。
