### ISSUE TITLE
「Laravel 6.x ブロードキャスト」の誤字

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#22]
「Laravel 6.x ブロードキャスト」
https://readouble.com/laravel/6.x/ja/broadcasting.html

「これによりそのエベントへ、アプリケーションの名前空間を付けないよう、Echoに指示します。」

「エベント」でなく、おそらく「イベント」。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
