### ISSUE TITLE
Laravel 6.x ブロードキャストの表現

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#23]
間違いでなく、少し気になった表現です。
修正の線引が分からないので、試しにレポートします。

 https://readouble.com/laravel/6.x/ja/broadcasting.html
Laravel 6.x ブロードキャスト

「最初に、ブロードキャスト通知チャンネルの使用のドキュメントをよく読んでください。」

 "の使用の" 「の」が連続する部分に、少々違和感がある。

First, be sure to read over the documentation on using the broadcast notification channel.
「まず、ブロードキャスト通知チャネルの使用に関するドキュメントを必ずお読みください。」(グーグル翻訳)

などいかがでしょうか。

**Comment by HiroKws** [comment]
ご指摘ありがとうございます。「の」の連続は２つまでにしております。実は他にも連続している箇所はたくさんあります。機会があるときに少しずつ推敲しています。

翻訳の最初は、原文が米国の通信販売のような乗りがあり、それに合わせて訳しました。原文の調子がフォーマルな方へ段々と変化するしていくのに合わせて、翻訳の調子も変更しています。そのため、全体の表現がチグハグな部分があります。

細かい表現については、今後の推考でページごとにまとめて行い、表現を統一します。

**Comment by HiroKws** [comment]
ありがとうございます。章の最後の部分は、途中で追加されたもので推敲が十分でありませんでした。多少、推敲を行い和文を調整しました。
