### ISSUE TITLE
コレクション 6.x Laravel  - unlessメソッド

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#24]
# コレクション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/collections.html

「unlessメソッドは最初の引数がtrueと評価されなくなるまで、コールバックを実行します。」
となっています。

「されなくなるまで」というのは繰り返し処理であるかのように勘違いしやすいのではないか。
このメソッド単体では

## 原文
The unless method will execute the given callback unless the first argument given to the method evaluates to true:
## google翻訳
「unlessメソッドは、メソッドに指定された最初の引数がtrueと評価されない限り、指定されたコールバックを実行します」

### ちなみに
逆の動作でもある when() では
「whenメソッドは、メソッドの第１引数がtrueに評価される場合、コールバックを実行します。」
となっています。

**Comment by HiroKws** [comment]
ありがとうございます。
