### ISSUE TITLE
コレクション - whenNotEmpty()

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#25]
# コレクション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/collections.html

# whenNotEmpty()
「whenNotEmptyメソッドは、コレクションがから出ない場合に、指定したコールバックを実行します。」
の
「コレクションがから出ない場合に」
は誤字で
「コレクションが空でない場合に」
などではないか。

**Comment by HiroKws** [comment]
ありがとうございます。
