### ISSUE TITLE
メール 6.x Laravel  - インライン添付

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#27]
#メール 6.x Laravel 
https://readouble.com/laravel/6.x/ja/mail.html

## インライン添付
「変数は平文メッセージでは使用できません。低文メッセージではインライン添付が利用できないためです。」
の
「低文」は「平文」の誤字と思われる。

**Comment by HiroKws** [comment]
ありがとうございます。
