### ISSUE TITLE
データベース：クエリビルダ   - 増減分の誤記

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#29]
Laravel 6.x データベース：クエリビルダ 
https://readouble.com/laravel/6.x/ja/queries.html

# 増減分
「これは短縮記法で、update分で書くのに比べるとより記述的であり、」
の
「update分」
は
「update文」の誤記と思われる。

**Comment by HiroKws** [comment]
ありがとうございます。
