### ISSUE TITLE
データベース：ペジネーションの誤植

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#30]
データベース：ペジネーション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/pagination.html

## ペジネーションリンクウィンドウの調整
「ペギネータのURL「ウィンドウ」の両サイドに、」
の
「ペギネータ」
は
「ペジネータ」の誤植と思われる。

**Comment by HiroKws** [comment]
ありがとうございます。
