### ISSUE TITLE
ペジネータインスタンスメソッドのタイポ

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#31]
データベース：ペジネーション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/pagination.html

## ペジネータインスタンスメソッド
$results->getPageName() の
「ページを保存するするために使用するクエリ文字変数を取得」
の
「するする」が多分タイポ

**Comment by HiroKws** [comment]
ありがとうございます。
