### ISSUE TITLE
マイグレーション 6.x Laravel  - collation

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#32]
データベース：マイグレーション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/migrations.html

## データベース接続とテーブル操作
「テーブルのデフォルトコロケーションの指定(MySQL)」
とあるが
「コロケーション」
ではなく
「コレーション(collation)」などと
と思われる。

**Comment by HiroKws** [comment]
ありがとうございます。
