### ISSUE TITLE
「イベントリスナ」にリンクが貼られている先が見つからない。

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#33]
Eloquent：利用の開始 6.x Laravel 
https://readouble.com/laravel/6.x/ja/eloquent.html

「Eloquentイベントの定義とマップができたら、イベントリスナを使用し、イベントを処理できます。」
という文章の「イベントリスナ」にリンクが貼られている先が見つからない。

https://laravel.comevents.html/#defining-listeners
というドメインなので、なにかおかしい気がする。

**Comment by HiroKws** [comment]
ありがとうございます。これは原文のミスです。当リポジトリは日米の差異を管理しない方針のため、原文が修正されるまでお待ち下さい。

**Comment by HiroKws** [comment]
勘違いでした。URLは原文のままでは都合が悪いためURIへ変更しているのですが、他の章も含め原文のままになっているところがありました。手作業で修正しているため、少々お待ち下さい。

**Comment by HiroKws** [comment]
修正完了しました。
