### ISSUE TITLE
Eloquent：リレーション のタイポ

### ISSUE THREAD

**Issue by aq-yoshimura** [laravel-ja/ja-docs-6.x#34]
Eloquent：リレーション 6.x Laravel 
https://readouble.com/laravel/6.x/ja/eloquent-relationships.html

## カスタム中間テーブルとIDの増分
「カスタム中間テーブルを使用し、他対多リレーションを定義しており、」
の
「他対多」が恐らくタイポ。

**Comment by HiroKws** [comment]
ありがとうございます。
