### ISSUE TITLE
シーディング時の複数代入の保護の無効化

### ISSUE THREAD

**Issue by crhg** [laravel-ja/ja-docs-6.x#4]
[データベース:シーディング→シーダクラス定義](https://readouble.com/laravel/6.0/ja/seeding.html#writing-seeders)に、

> Tip!! データベースシーディング時、複数代入は自動的に無効になります

とありますが、原文は

> Tip!! Mass assignment protection is automatically disabled during database seeding.

なので、無効になるのは「複数代入」ではなく「複数代入からの保護」だと思います。

誤操作で入力しかけでissueを作成してしまったことをお詫びします。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。readouble.comへの反映は数分お待ちください。
