### ISSUE TITLE
外部キー制約のサフィックスの誤記

### ISSUE THREAD

**Issue by na3shkw** [laravel-ja/ja-docs-6.x#41]
https://readouble.com/laravel/6.x/ja/migrations.html#foreign-key-constraints

「"\\_foreign"を最後につけた名前」となっており、原文にないバックスラッシュが含まれています。

**Comment by HiroKws** [comment]
ありがとうございます。Markdownをｈｔｍｌへ変更するために使用しているスクリプト言語かpandocのエスケープの振る舞いが変更されていたようです。翻訳中のエスケープを標準的なものに変更しました。
