### ISSUE TITLE
Bladeテンプレートの レイアウト拡張でtypoがあります。

### ISSUE THREAD

**Issue by myaosato** [laravel-ja/ja-docs-6.x#5]

**Comment by myaosato** [comment]
ご送信で、Issueを開いてしまって申し訳ないです。

https://readouble.com/laravel/6.0/ja/blade.html#extending-a-layout
にタイポがあります。

具体的には、`@parent`となるべきところが、`@@parent`となっているように思います。

私が確認した限りでは、5.1から6.0まで全てで起こっています。

こちらのリポジトリの原文の英語の時点で、すでに`@@parent`となっています。

https://readouble.com/laravel/6.0/en/blade.html#extending-a-layout

参考: https://laravel.com/docs/6.x/blade#extending-a-layout

**Comment by HiroKws** [comment]
報告ありがとうございます。readmeにも書いてありますが、翻訳は英語版の原文を元にしています。

英語版の原文とはGitHubのlaravel/docsリポジトリのことです。　https://github.com/laravel/docs/blob/6.x/blade.md#extending-a-layout

こちらでは、修正されていません。ですから、先行して日本語翻訳を修正しません。リポジトリに反映されるまでお待ちください。

リポジトリと異なった内容がLaravelのドキュメントで表示されるのは、開発チームのワークフローの問題ですので、こちらでは対処できません。ご了承ください。

**Comment by myaosato** [comment]
なるほど。ちゃんと理解していませんでした。申し訳ない。
