### ISSUE TITLE
queueのretry_afterの記述に関しまして

### ISSUE THREAD

**Issue by sdkawata** [laravel-ja/ja-docs-6.x#8]
こちらに以下のように記述されていますが
https://readouble.com/laravel/6.x/ja/queues.html#job-chaining

> たとえば、retry_afterの値が90であれば、そのジョブは処理が終わってから９０秒の間に削除されなければ、キューへ再投入されます。

英文には以下のようにあり、
https://laravel.com/docs/6.x/queues#job-chaining

> For example, if the value of retry_after is set to 90, the job will be released back onto the queue if it has been processing for 90 seconds without being deleted.

以下のように訳出するほうが正確でわかりやすいかと思いましたが、いかがでしょうか。

> たとえば、retry_afterの値が90であれば、そのジョブは９０秒の間に削除されることなく処理され続ければ、キューへ再投入されます。

**Comment by HiroKws** [comment]
ありがとうございます。sleepオプションの概念が頭にあったため、このように訳してました。

前後を含め段落を以下のように変更します。

~~~~
`config/queue.php`設定ファイルの中で、各キュー接続は`retry_after`オプションを定義しています。このオプションは処理中のジョブを再試行するまで、キュー接続を何秒待つかを指定します。たとえば、`retry_after`の値が`90`であれば、そのジョブは９０秒の間に削除されることなく処理され続ければ、キューへ再投入されます。通常、`retry_after`値はジョブが処理を妥当に完了するまでかかるであろう秒数の最大値を指定します。
~~~~

反映まで少々お待ちください。
