### ISSUE TITLE
ページ"HTTPリクエスト"内の項目"リクエストからクッキーを取得"のタイポ

### ISSUE THREAD

**Issue by junichimura** [laravel-ja/ja-docs-6.x#9]
▼問題箇所
https://readouble.com/laravel/6.x/ja/requests.html#cookies

▼問題内容
以下の箇所について日本語入力時のタイポと思われる箇所がありました。

・英語元文
>「All cookies created by the Laravel framework are encrypted and **signed** with an authentication code,」

・誤:  
>「Laravelフレームワークが作成するクッキーは全て暗号化され、認証コードで**著名**されています。」

・正:
>「Laravelフレームワークが作成するクッキーは全て暗号化され、認証コードで**署名**されています。」

▼その他
Mr. @HiroKws をいつも応援しています。

**Comment by HiroKws** [comment]
ありがとうございました。修正いたしました。
